### ISSUE TITLE
Library not compiling on no_std

### ISSUE THREAD

**Issue by barafael** [mjaakkol/sgp40-rs#1]
Hi!
I noticed that this library does not seem to compile in an no_std environment. The abs, sqrt, and friends of f32 in vocalg are to blame. I am not sure how this should be resolved, but FWIW here is a demo of what does not work:

1. Clone https://github.com/barafael/sgp40-rs
2. cd examples/nrf52-example
3. cargo build

Perhaps if the f32 logic cannot be included (via libm), the vocalg stuff could be made a selectable feature.

**Comment by mjaakkol** [comment]
I'll make the feature configurable over the weekend (or earlier) and release new update.

I'll look into porting the library into FixedPoint Rust implementation with no-std. Not sure when I can do that as the original implementation was God awful hassle to do.

Stay tuned.

**Comment by barafael** [comment]
Interesting! I'll look into that as well, for my (also sensirion) sdp800 lib. Didn't know this was a thing, thanks!

**Comment by mjaakkol** [comment]
The implementation of the algorithm is based on https://github.com/Sensirion/embedded-sgp/tree/master/sgp40_voc_index so I haven't come up with that but just ported it to Rust-native. I'll either implement sufficient libfixmath library functions or use an existing Rust crate like https://crates.io/crates/fixed and implement exp on top of it.

**Comment by mjaakkol** [comment]
Version 0.0.2 has VOC index calculation as an optional feature. It is turned off by default so if you don't need/want the feature, you can turn it off by removing defaults from the crate.

I'll look into converting VOC index calculation into no-std in upcoming days.
